create table employees(
	id serial primary key,
	employee_name varchar(50) not null
);
insert into employees(employee_name)
values ('Juan Alexander'),
	   ('Sergio Rodriguez'),
	   ('Belinda Carter'),
	   ('Jameson Henderson'),
	   ('Urszula Johnson'),
	   ('Yaeko Hall'),
	   ('Felix Lewis'),
	   ('Tori Garcia'),
	   ('Trey Price'),
	   ('Francesca Lewis'),
	   ('Watson Hayes'),
	   ('Natalya Perez'),
	   ('Price Carter'),
	   ('Kiara Lopez'),
	   ('Darren Brooks'),
	   ('Donovan Young'),
	   ('Francisca Mitchell'),
	   ('Erik Griffin'),
	   ('Fletcher Martinez'),
	   ('Deanna Reed'),
	   ('Oakleigh Flores'),
	   ('Evelynn Perez'),
	   ('Zavier Smith'),
	   ('Trent Gray'),
	   ('Ricardo Collins'),
	   ('Salma Diaz'),
	   ('Kieran Price'),
	   ('Savannah Collins'),
	   ('Yanet Flores'),
	   ('Turner Long'),
	   ('Fiona Powell'),
	   ('Varden Flores'),
	   ('Rivka Coleman'),
	   ('Norah Reed'),
	   ('Arabella Lee'),
	   ('Francesco Alexander'),
	   ('Kathryn Wood'),
	   ('Nahla Long'),
	   ('Patricio White'),
	   ('Vesper Roberts'),
	   ('Odelia Perry'),
	   ('Tripp Bell'),
	   ('Niklaus Lewis'),
	   ('Izabelle Harris'),
	   ('Bella Brown'),
	   ('Kendra Jackson'),
	   ('Darren Brooks'),
	   ('Fallyn Hayes'),
	   ('Levi Martin'),
	   ('Ulva Gonzales'),
	   ('Niklaus Lewis'),
	   ('Belen Patterson'),
	   ('Angelo Lewis'),
	   ('Wynter Edwards'),
	   ('Josephine Harris'),
	   ('Hank Gonzales'),
	   ('Yana Phillips'),
	   ('Sergio Davis'),
	   ('Elliana Bell'),
	   ('Nash Butler'),
	   ('Rosalyn Carter'),
	   ('Vermont James'),
	   ('Farida Richardson'),
	   ('Henley James'),
	   ('Jayla Powell'),
	   ('Rocco Bryant'),
	   ('Xenophon Cox'),
	   ('Guinevere Alexander'),
	   ('Wesley James'),
	   ('Masha Kostsina');
select * from employees;
create table salary(
	id serial primary key,
	monthly_salary Int not null
);
insert into salary(monthly_salary)
values (1000),
       (1100),
       (1200),
       (1300),
       (1400),
       (1500),
       (1600),
       (1700),
       (1800),
       (1900),
       (2000),
       (2100),
       (2200),
       (2300),
       (2400),
       (2500);
select * from salary;

create table employee_salary(
id serial primary key,
employee_id int not null unique,
salary_id int not null
);
insert into employee_salary(employee_id, salary_id)
values (3, 7),
	   (1, 4),
	   (5, 9),
	   (40, 13),
	   (23, 4),
	   (11, 2),
	   (52, 10),
	   (15, 13),
	   (26, 4),
	   (16, 1),
	   (33, 7),
	   (37, 4),
	   (12, 2),
	   (19, 10),
	   (43, 13),
	   (70, 15),
	   (6, 16),
	   (17, 2),
	   (2, 5),
	   (64, 8),
	   (67, 3),
	   (54, 6),
	   (8, 11),
	   (30, 12),
	   (13, 14),
	   (7, 16),
	   (31, 8),
	   (42, 13),
	   (25, 2),
	   (9, 5),
	   (71, 10),
	   (72, 1),
	   (73, 7),
	   (74, 16),
	   (75, 3),
	   (76, 12),
	   (77, 11),
	   (78, 14),
	   (79, 6),
	   (80, 15);
select * from employee_salary;
	 
create table roles(
id serial primary key,
role_name int not null unique
);
alter table roles alter column role_name type varchar(30);
insert into roles(role_name)
values ('Junior Python developer'),
	   ('Middle Python developer'),
	   ('Senior Python developer'),
	   ('Junior Java developer'),
	   ('Middle Java developer'),
	   ('Senior Java developer'),
	   ('Junior JavaScript developer'),
	   ('Middle JavaScript developer'),
	   ('Senior JavaScript developer'),
	   ('Junior Manual QA engineer'),
	   ('Middle Manual QA engineer'),
	   ('Senior Manual QA engineer'),
	   ('Project Manager'),
	   ('Designer'),
	   ('HR'),
	   ('CEO'),
	   ('Sales manager'),
	   ('Junior Automation QA engineer'),
	   ('Middle Automation QA engineer'),
	   ('Senior Automation QA engineer');
create table roles_employee(
id serial primary key,
employee_id int not null unique,
role_id int not null,
foreign key (employee_id) references employees (id),
foreign key (role_id) references roles (id)
);
select * from roles_employee;
insert into roles_employee(employee_id, role_id)
values (7, 2),
       (20, 4),
       (3, 9),
       (5, 13),
       (23, 4),
       (11, 2),
       (10, 9),
       (22, 13),
       (21, 3),
       (34, 4),
       (6, 7),
       (70, 19),
       (30, 10),
       (44, 20),
       (18, 14),
       (60, 1),
       (53, 16),
       (66, 8),
       (51, 17),
       (49, 11),
       (37, 15),
       (13, 6),
       (56, 5),
       (40, 12),
       (25, 18),
       (8, 17),
       (33, 8),
       (47, 11),
       (62, 16),
       (15, 15),
       (1, 1),
       (28, 6),
       (41, 14),
       (59, 5),
       (69, 20),
       (64, 12),
       (16, 10),
       (19, 18),
       (50, 7),
       (45, 19);
select * from roles_employee;
       